version: "3.7"
services:

  graphite:
    image: graphiteapp/graphite-statsd
    ports:
      - "2003-2004:2003-2004"
      - "2023-2024:2023-2024"
      - "8125:8125/udp"
      - "8126:8126"

  grafana:
    image: sysdiglabs/grafana
    ports:
      - "3000:3000"
    environment:
      GF_SERVER_ROOT_URL: 'http://grafana.test'
      GF_SECURITY_ADMIN_PASSWORD: 'secret'

